#!/bin/zsh
# Lifted from https://github.com/lukaszkorecki/DotFiles/blob/master/bins/faces
faces=(
    'ಠ_ಠ'
    'ಠ_ರೃ'
    'ಠ▃ಠ'
    '(•‿•)'
    'Ծ_Ծ'
    '(✌ﾟ∀ﾟ)☞'
    't(-_-t)t'
    '¯\_(ツ)_/¯'
    ';ლ(ಠ_ಠლ)'
    '(╯°□°）╯︵ ┻━┻'
    'ᶘ ᵒᴥᵒᶅ'
    'ლ(́◉◞౪◟◉‵ლ)'
    '( ͝° ͜ʖ͡°)'
    '(╯°□°)╯'
    '( ︶︿︶)'
    '(ノ・∀・)ノ'
)

if [[ -z $1 ]]; then
  echo 'Choose a face and copy it with xclip'
  i=1
  for f in ${faces[@]}
  do
    echo $i $f
    i=`expr $i + 1`
  done
else
  echo ${faces[$1]}
  echo -n ${faces[$1]} | xclip -selection clipboard
fi
